# Generated by Django 4.2.26 on 2025-11-15 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='A brief bio of the character.')),
                ('age', models.IntegerField(blank=True, help_text='Can be null', null=True)),
                ('birthday', models.DateField(blank=True, help_text="Character's birthday", null=True)),
                ('is_samurai', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='api.character')),
            ],
        ),
    ]
